services:
# --- INSTANCE 1 ---
  rooms_service_1:
    build: .
    command: python rooms_service/app.py
    # We DO NOT expose ports here. Only Nginx communicates with them.
    environment:
      - DATABASE_URL=postgresql://admin:securepassword123@db:5432/meeting_room_db
    depends_on:
      - db

  # --- INSTANCE 2 ---
  rooms_service_2:
    build: .
    command: python rooms_service/app.py
    # Identical configuration to Instance 1
    environment:
      - DATABASE_URL=postgresql://admin:securepassword123@db:5432/meeting_room_db
    depends_on:
      - db

  # --- LOAD BALANCER ---
  nginx:
    image: nginx:latest
    ports:
      - "4000:80"  # We access the app via localhost:4000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rooms_service_1
      - rooms_service_2

  # 1. Database
  db:
    image: postgres:15
    container_name: meeting_room_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d meeting_room_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # 6. Redis Cache
  redis:
    image: redis:alpine
    container_name: meeting_room_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Users Service
  users_service:
    build: .
    command: python users_service/app.py
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Tells Python to look for the container named 'db' instead of 'localhost'
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      BOOKINGS_API_URL: http://bookings_service:5003/bookings
      # Pass the encryption key
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}

  # 3. Rooms Service
  rooms_service:
    build: .
    command: python rooms_service/app.py
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      REDIS_URL: redis://redis:6379/0 # Redis connection for caching
      PYTHONUNBUFFERED: 1
  # 4. Bookings Service
  bookings_service:
    build: .
    command: python bookings_service/app.py
    ports:
      - "5003:5003"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}

  # 5. Reviews Service
  reviews_service:
    build: .
    command: python reviews_service/app.py
    ports:
      - "5004:5004"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}

volumes:
  postgres_data: